// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1pcnoBXfgLHqFzC0-3uZnrPiuRvxpnTQ',
    appId: '1:993254387807:web:87003ee97ac653745b6bea',
    messagingSenderId: '993254387807',
    projectId: 'docsreminder',
    authDomain: 'docsreminder.firebaseapp.com',
    storageBucket: 'docsreminder.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe6flL3_N8bixvtRlq8wcxUS1-ua-PlO4',
    appId: '1:993254387807:android:ae7184ea88f1e1b75b6bea',
    messagingSenderId: '993254387807',
    projectId: 'docsreminder',
    storageBucket: 'docsreminder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCyMjn_W5Ku0CUbm-pDg6wYFR9PZSt6MI',
    appId: '1:993254387807:ios:513276bdeea6dc705b6bea',
    messagingSenderId: '993254387807',
    projectId: 'docsreminder',
    storageBucket: 'docsreminder.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCyMjn_W5Ku0CUbm-pDg6wYFR9PZSt6MI',
    appId: '1:993254387807:ios:513276bdeea6dc705b6bea',
    messagingSenderId: '993254387807',
    projectId: 'docsreminder',
    storageBucket: 'docsreminder.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1pcnoBXfgLHqFzC0-3uZnrPiuRvxpnTQ',
    appId: '1:993254387807:web:1459c201dbf6b5cc5b6bea',
    messagingSenderId: '993254387807',
    projectId: 'docsreminder',
    authDomain: 'docsreminder.firebaseapp.com',
    storageBucket: 'docsreminder.firebasestorage.app',
  );
}
